# .readthedocs.yaml
version: 2

mkdocs:
  configuration: Documentation/mkdocs.yaml

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - doxygen
    - graphviz
  jobs:
    # This replaces the default RTD build step with a verbose one
    build:
      html:
        - python -m mkdocs build -v --clean --site-dir $READTHEDOCS_OUTPUT/html --config-file Documentation/mkdocs.yaml

python:
  install:
    - requirements: Documentation/requirements.txt

